version: "3.8"

services:
  frontend:
    container_name: client-frontend
    build: 
      context: ./frontend
      args:
        SERVER_ADDR: ${SERVER_ADDR:-localhost:8080}
    ports:
      - 1234:1234
