version: "3.8"

services:
  yarilo-dev:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile.dev
    command: ./run.sh --sniff_file=/app/src/backend/pcap/wpa_induction.pcap
    ports:
      - 8080:8080
      - 25565:9090
    volumes:
      - .:/app/src
      - build_data:/app/build

volumes:
  build_data:
