services:
  yarilo:
    image: typicalam/yarilo:latest
    command: --sniff_file=/tmp/pcap/wireshark_sample.pcap --save_path=/app/saves --db-path=/app/saves/yarilo_database.db
    volumes:
      - /tmp/saves:/app/saves
      - ./pcap:/tmp/pcap
    network_mode: host # Note: This works only on linux
    cap_add:
      - NET_ADMIN

  yarilo-front:
    image: typicalam/yarilo-front:latest
    ports:
      - 80:3000
