version: "3.8"

services:
  sniffer-dev:
    build: 
      context: ./
      dockerfile: ./backend/Dockerfile.dev
    command: sh run.sh --fromfile --filename=/opt/app/backend/pcap/wpa_induction.pcap
    volumes:
      - .:/opt/app
      - build_data:/opt/build

  proxy:
    build: 
      context: ./proxy
      args:
        CONFIG_FILE: envoy_dev.yaml
    ports:
      - 8080:8080
    links:
      - sniffer-dev

volumes:
  build_data:
