services:
  yarilo:
    image: typicalam/yarilo:latest
    command: ./run.sh $YARILO_EXTRA_ARGS
    volumes:
      - /tmp/saves:/tmp/saves
      - ./pcap:/tmp/pcap
    network_mode: host # Note: This works only on linux
    cap_add:
      - NET_ADMIN

  yarilo-front:
    image: typicalam/yarilo-front:latest
    ports:
      - 80:3000
