services:
  yarilo-dev:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
      target: development
      args:
          BATTERY_SUPPORT: ON
    command: --sniff_file=/src/pcap/wireshark_sample.pcap --save_path=/app/saves
    ports:
      - 8080:8080 # Envoy (for grpc-web)
      - 9090:9090 # Yarilo
    volumes:
      - .:/src
      - ./dev-save-data:/app/saves
      - /tmp/battery_level:/tmp/battery_level
