version: "3.8"

services:
  frontend:
    container_name: client-frontend
    build: 
      context: ./frontend
      args:
        PROXY_ADDR: ${PROXY_ADDR:-localhost:8080}
    ports:
      - 1234:1234

volumes:
  build_data:
