name: Build Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: typicalam
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "typicalam/yarilo:latest,typicalam/yarilo:${{ github.ref_name }}"
          platforms: linux/amd64,linux/arm64
          file: ./backend/Dockerfile

  backend-battery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: typicalam
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "typicalam/yarilo:latest-hardware,typicalam/yarilo:${{ github.ref_name }}-hardware"
          platforms: linux/amd64,linux/arm64
          file: ./backend/Dockerfile
          build-args:
            BATTERY_SUPPORT=ON

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: typicalam
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "typicalam/yarilo-front:latest,typicalam/yarilo-front:${{ github.ref_name }}"
          platforms: linux/amd64,linux/arm64
          file: ./frontend/Dockerfile

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: typicalam
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "typicalam/yarilo-docs:latest,typicalam/yarilo-docs:${{ github.ref_name }}"
          platforms: linux/amd64,linux/arm64
          file: ./backend/Dockerfile.docs
